eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerPort: 8761
    eurekaServerURLContext: eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 2225